"""add email_data table

Revision ID: 91d393ed1205
Revises: e84a7d29e98f
Create Date: 2022-10-23 21:04:12.069835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d393ed1205'
down_revision = 'e84a7d29e98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
