---
- name: 'MySQL | Get master file and position | mysql1'
  mysql_replication:
    login_host: '{{ address_mysql1 }}'
    login_user: '{{ user }}'
    login_password: '{{ password }}'
    mode: getmaster
  register: mysql_repl_mysql1

- name: 'MySQL | Change Master Status | mysql2'
  command: mysql -u root -e "STOP SLAVE; CHANGE MASTER TO MASTER_HOST='{{ address_mysql1 }}', MASTER_USER='{{ user }}', MASTER_PASSWORD='{{ password }}', MASTER_LOG_FILE='{{ mysql_repl_mysql1.File }}', MASTER_LOG_POS = {{ mysql_repl_mysql1.Position }}; START SLAVE;"
