---
- hosts: mysql
  become: no
  become_method: sudo

  roles:
    - role: setup-mysql
      become: yes

- hosts: mysql1
  become: no
  become_method: sudo

  roles:
    - role: configure-mysql1
      become: yes

- hosts: mysql2
  become: no
  become_method: sudo

  roles:
    - role: configure-mysql2
      become: yes

- hosts: backend
  become: no
  become_method: sudo

  roles:
    - role: setup-backend
      become: yes

- hosts: haproxy
  become: no
  become_method: sudo

  roles:
    - role: setup-haproxy
      become: yes
