name: send-email
on:
  push: # event push
    branches: [master]

jobs: # chuoi cac task dinh nghia de chay
  docker:
    runs-on: ubuntu-latest # moi truong chay
    steps: # tasks nho trong job day
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with: # truyen thong tin tham so
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/send-email

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

  update_ssh_backend:
    name: Telling server backend to Update
    needs: 'push_to_registry'
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST1 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS1 }}
          port: 22
          script: sudo bash update.sh

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST2 }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS2 }}
          port: 22
          script: sudo bash update.sh
